INSERT INTO services (name, description, base_price, price_model, type, sort_order) VALUES
    ('Website Launch',
     'Professionelle Website – individuell designt, mobil-optimiert und auf Ergebnisse ausgerichtet.',
     2500.00, 'einmalig', 'paket', 1),
    ('Local Growth',
     'Google Business Optimierung, Local SEO und Bewertungsmanagement.',
     500.00, 'monatlich', 'paket', 2),
    ('KI Assist',
     'KI-Tools die rund um die Uhr arbeiten – von Chatbot bis Telefonassistent.',
     800.00, 'monatlich', 'paket', 3),
    ('Content & Social Posts',
     'KI-generierter Content für Social Media & Blog.',
     300.00, 'monatlich', 'addon', 10),
    ('E-Mail-Automatisierung',
     'Automatisierte Kampagnen mit intelligenter Segmentierung.',
     250.00, 'monatlich', 'addon', 11),
    ('Analytics & Insights',
     'Dashboard mit KI-Auswertungen und Handlungsempfehlungen.',
     200.00, 'monatlich', 'addon', 12),
    ('Online-Shop',
     'E-Commerce mit Bezahlung, Versand & Bestellverwaltung.',
     3500.00, 'einmalig', 'addon', 13);
